# Generated by Django 5.0.4 on 2024-04-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_cartitem_selected_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="selected_date",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
