# Generated by Django 5.0.4 on 2024-04-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_cartitem_selected_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="selected_date",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
