# Generated by Django 5.0.4 on 2024-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_customer_last_name_customer_selected_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="paymentM",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="customer",
            name="paymentM",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
